- build.sh
- dockerd-starting.sh
- get_env.sh
- push_COS.sh
- test-staging-DEBS/Dockerfile
- test-staging-RPMS/Dockerfile
- test.sh
- test_staging.sh
The static build command now needs the version number of containerd specified and in the case where there is no new containerd version, CONTAINERD_VERS was supposed to be equal to 0 to avoid building it.
Fix : CONTAINERD_VERS will always take the version number of containerd whether we build the dynamic packages or not and CONTAINERD_BUILD will be equal to 0 if we don't want to build the dynamic packages (and we check in that case, if we already built containerd for all distributions, identified for docker-ce-packaging)
> Fix static build when CONTAINERD_VERS=0

- build-docker.sh
- check-tests.sh
- env/env.list
- env/test-release.list
- env/test-staging.list
- get-env.sh
- prow-build-containerd.sh
- prow-test-docker.sh
- push-COS.sh
- test.sh
- Cleanup traces for parallel docker build
- Add trigger files for the jobs postsubmit-test-docker-staging, postsubmit-test-docker-release
- Enable test for static packages only for local test mode
- Add new settings in env/env.list:
* `DISABLE_DISTRO_DISCOVERY`: Disable linux distribution automatic discovery from the [docker-ce-packaging](https://github.com/docker/docker-ce-packaging) repo.
This allows to manually  specify the distro list by settings the value for $RPMS and $DEBS.
* `DISABLE_PUSH_COS`: Disable push of the packages to the COS bucket shared with Docker team
* `COS_BUCKET_SHARED`, URL_COS_SHARED : COS bucket shared with Docker team settings
- Enable test for static packages only for local `test `mode (disable it for the other modes `staging` and `release`)
> Add new settings DISABLE_DISTRO_DISCOVERY, DISABLE_PUSH_COS

- env/env.list
Made a typo for the  DOCKER_VERS="v20.10.14" in the env.list . The heading 'v' was missing.
> Fix typo on Docker version in env.list

- build-containerd.sh
- env/env.list
* Disable push to shared COS bucket (the script is broken).
* Rename GOLANG_VERSION shell variable to CONTAINERD_GO_VERSION
The GOLANG_VERSION  variable is also used in containerd-packaging](https://github.com/docker/containerd-packaging/blob/825bb846ee12f0f0433c7289f1fcbd37040a91a1/common/common.mk#L22) and causing side effects, 
When GOLANG_VERSION is set to "" in env.list, this was causing the  GOLANG_VERSION environment variable to be set to "" and made the build failing as the golang version was set to empty as depicted below:
```
Building packages on docker.io/library/debian:bullseye
containerd   : v1.5.11 (commit: 3df54a8)
INFO: detected runc version (v1.0.3) from script/setup/runc-version
runc         : v1.0.3 (commit: f46b6ba)
architecture : ppc64le
build image  : …
```
> Fix side effect with Go version variable

- test-containerd/instanciate_powervs_vm.sh
- test-containerd/test_on_powervs.sh
Add "FAIL:" when ``exit 1``  in order to check error directly in text file for parallel processing.
> Change error message in order to check error in text files easily.

- build-containerd.sh
- env/env.list
- test.sh
- Also fix for CentOS stream 9 that must be retrieved from quay.io (not available docker hub)
- Enable push to COS
> Build docker 20.10.15 and containerd 1.6.4

- env/test-staging.list
Spinning the test staging job again, as the 1st failed because of COS bucket access failure.
See https://prow.ppc64le-cloud.org/view/s3/prow-logs/logs/postsubmit-test-docker-staging/1527688752099495936
```
+ /home/prow/go/src/github.com/ppc64le-cloud/docker-ce-build/get-env-containerd.sh
cp: cannot access '/mnt/s3_ppc64le-docker/prow-docker/dockertest': Software caused connection abort
...
Build log for debian-bullseye copied to the COS bucket
+ cp /workspace/tests/build_debian_bullseye.log /mnt/s3_ppc64le-docker/prow-docker/build-docker-v20.10.16_180522-1607/tests-staging
cp: failed to access '/mnt/s3_ppc64le-docker/prow-docker/build-docker-v20.10.16_180522-1607/tests-staging': Transport endpoint is not connected
+ echo '### ## Running the tests from the container: …
```
> Spin test staging for docker 20.10.15, containerd 1.6.4, 2d attempt

- build-docker.sh
- Remove ubuntu-impish from the list of Distros
- Use the number of CPUs for the "max" parallelism
> Improve parallelism

- test-containerd/test_on_powervs.sh
The default test timeout of ten minutes is too short, causing some tests to fail. Change the test timeout value to thirty minutes to allow time for all tests to complete.
> Modify go test timeout

- test-containerd/test_on_powervs.sh
Run script/setup/install-failpoint-binaries script before running containerd tests to allow TestRunPodSandboxWithSetupCNIFailure and TestRunPodSandboxWithShimStartFailure tests to run properly
> Add failpoint setup script

- env/env.list
- get-env-containerd.sh
- prow-test-docker.sh
- test-launch.sh
- test.sh
* Fix issue  #52 by adding a touch to the Dockerfiles used for launching the tests.
This changes the timestamp of the Dockerfile, which makes Docker consider those Dockerfiles different from each other and do not  reuse any cached data when building the test images.
* Also fix the use of  CONTAINERD_BUILD=0 and provided usage comment in env/env/list
*  Added a `local` option to prow-test-docker.sh, so that we can re-test the packages by grabbing them from the COS bucket
> Fix gotestsum error for the docker packaging tests

- build-containerd.sh
- build-docker.sh
- env/env.list
- Override runc version to v1.1.4 for containerd, RUNC_REF
- Patch Go image to bullseye in build-docker.sh due to Debian bullesye EOL
- Update env.list for building docker 20.10.18 and containerd 1.6.8
> Build docker 20.10.18 and containerd 1.6.8

- test-containerd/instanciate_powervs_vm.sh
- test-containerd/test_on_powervs.sh
Containerd integration test suite failures on PowerVS are fixed by increasing the allocated memory and processor resources and adding some additional configuration before test suites are executed.
> Powervs Memory Increase

- build-static.sh
Patch the Makefile to use golang of bullseye instead of EOL buster in static build.
> Fix the static build golang issue dueto buster EOL

- env/env.list
Docker version 20.10.18 requires Runc 1.1.4 and containerd 1.6.8
Containerd version 1.6.8 requires Runc 1.1.4 and Go 1.17.13
> Re-build/test now that static build failure fixed

- test-containerd/instantiate_vm_and_test.sh
Increase wait time to 6 minutes before attempting to access a new VM via ssh.
> Increase wait time before attempting ssh

- test.sh
Due to buildkit/gotestsum issue.
> Reduce parallelization: nCPUs/2

- test-containerd/instantiate_vm_and_test.sh
Check ssh-keyscan success to prevent an unsuccessful keyscan from exiting the script.
> Check ssh-keyscan success

- test-containerd/instantiate_vm_and_test.sh
A new public network will be created for new PowerVS instances at the start of each test. New PowerVS instances will no longer depend on an existing public network.
> Fix vm networking

- env/test-staging.list
Retest Docker 23.0.0 in staging due to Fedora 37 test timeout.
> Retest Docker 23.0.0 in staging

- env/env.list
Rebuilding Docker v23.0.1 and containerd v1.6.18 due to failures seen while testing Fedora - 36
> Rebuild Docker v23.0.1 and containerd v1.6.18

- build-docker.sh
This change will display an error message in case the script cannot create a directory to copy builds to on the COS bucket due to any reason.
> Display an error message and exit when copying to COS bucket fails.

- build-docker.sh
- env/env.list
Introduced DOCKER_BUILD env var which when unset will only build containerd and will build both, docker and containerd when set.
> Introduced DOCKER_BUILD env var which when unset will only build

- build-docker.sh
- prow-build-test-containerd.sh
If DOCKER_BUILD is set to 0, Docker packages are not built and hence tests should not be performed as these packages will not be found. This pull request skips these tests if DOCKER_BUILD is set to 0.
> Only perform tests if Docker packages are built and not otherwise.

- env/env.list
Building Docker v20.10.24 and containerd v1.6.20 simultaneously to let tests run successfully.
> Build Docker v20.10.24 and containerd v.1.6.20

- env/test-release.list
Retesting Docker v20.10.24 in release as the Docker daemon did not start resulting in test failures for some distributions.
> Retest Docker v20.10.24 in release

- check-tests.sh
- env/env.list
Certain distributions have reached end of life and are yet discovered by the code from the upstream repository. This commit helps the code skip through those distributions. This is being done to fix an issue where the packages do not get automatically pushed to the shared COS bucket as the code refuses to copy over any packages if there is any error thrown at any point through the build process.
> Fix Automatic Pushing of Builds to shared COS bucket

- env/env.list
Rebuilding Docker v20.10.24 to test https://github.com/ppc64le-cloud/docker-ce-build/pull/90.
> Testing PR 90: Fix push COS

- test-containerd/instantiate_vm_and_test.sh
Avoid job failures caused by PowerVS netoworking management errors. This stops the entire prow job from failing despite the fact that all containerd tests pass.
If removing the PowerVS network fails, the removal is retried a maximum of ten times.
> Avoid job failure caused by networking

- env/test-staging.list
Retesting Docker v23.0.4 in staging due to several test failures (network problems and Docker Daemon did not start)
> Retest Docker 23.0.4 in staging

- env/test-staging.list
> Retest Docker v23.0.4

- env/test-staging.list
Retesting due to gotestsum: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by gotestsum) error
> Retest Docker v23.0.4 in staging

- test-containerd/instantiate_vm_and_test.sh
Do not delete the test instance when SSH fails. This will allow for further investigation and testing into connection issues.
> Retain VM when SSH fails

- check-tests.sh
Static tests of Docker builds for Linux Alpine are only performed during local tests. Hence, increment one to the number of distributions which has been decremented an additional one time for Alpine since it is under "Exclusions". However, during local tests, Linux Alpine is not to be excluded.
> Check for alpine tests only during local tests

- env/env.list
Build Docker v23.0.5 and temporarily build the latest containerd packages as well because if they are not built, all tests fail.
> Build Docker 23.0.5

- env/test-staging.list
Retesting Docker v23.0.5 in staging as containerd.io could not be found by yum while testing Fedora 38.
> Retest Docker v23.0.5 in staging

- env/env.list
Rebuild containerd v1.6.21 due to failures. These failures occurred due to an incorrectly specified RUNC_REF (missing a v before the version number).
> Rebuild containerd v1.6.21

- test-containerd/instantiate_vm_and_test.sh
Modify network delete function to retry delete operation when it fails. This will allow the delete operation to be retried even when the ssh connection fails.
> Change network delete function

- env/test-staging.list
Running staging tests on Docker v23.0.5 again. The last time containerd packages were not available for Fedora 38 resulting in test failures. Containerd for Fedora 38 is now available.
> Test staging Docker v23.0.5

- env/env.list
Rebuild Docker v24.0.2 due to failure to build Centos-8 packages.
> Rebuild Docker v24.0.2

- env/env.list
Rebuilding Docker v24.0.2 for CentOS Stream 8 to see if systemd-pam accepts a more recent version of systemd.
> Rebuild Docker v24.0.2 only for CentOS Stream 8

- env/test-staging.list
Random GLIBC failure only now affects one build, should hopefully clear up this time.
> Retest staging Docker v24.0.3 due to centos-8 failure

- env/test-staging.list
CentOS Stream 8 tests still fail due to transient GLIBC error
> Retest staging Docker v24.0.3 to counter centos-8 failure

- env/test-staging.list
CentOS Stream 8 tests fail due to GLIBC error.
> Retest staging Docker v24.0.3

- README.md
The prow's URL has been changed to `.cis.ibm.net` from `.org`
> Change the prow dashboard url from .org to .cis.ibm.net

- test-containerd/test_on_powervs.sh
Install the appropriate version of the Go language. Containerd tests began to fail as containerd now uses new features and libraries from Go version 1.20, while the PowerVS VMs used for testing currently have Go version 1.19 installed by default. Upgrade Go to version 1.21.0 to allow tests to run successfully.
> Install new Go language version

- env/env.list
Build Docker v24.0.6 with the updated Docker image.
> Build Docker v24.0.6

- test-containerd/instantiate_vm_and_test.sh
Update the OS image to ubuntu 22.04, fixing failing tests due to an old kernel version. New tests require a kernel version >= 5.12, while the old OS image had a kernel version of 5.4.
> Update OS image

- README.md
- build-containerd.sh
- build-docker.sh
- build-static.sh
- env/env.list
- get-env-containerd.sh
- get-env.sh
- push-COS.sh
- test.sh
1. We currently use the `DOCKER_REF` environment variable for mentioning the tag that will be used to checkout `Docker CLI` and `Docker Engine`. This pull request decouples these into two new environment variables; `DOCKER_CLI` and `DOCKER_ENGINE` which contain the git hashes for the [Docker CLI](https://github.com/docker/cli) and [Docker Engine](https://github.com/moby/moby/) repositories separately to reduce reliance on tags.
2. We currently have a single environment variable `CONTAINERD_REF` which contains the tag to the [CONTAINERD repository](https://github.com/containerd/containerd). This pull request replaces this with two variables, `CONTAINERD_TAG` (to create directories on the COS buckets for naming these built packages) and `CONTAINERD_HASH` for actually checking out the …
> Use git hashes

- build-static.sh
This fixes the bug that causes static builds to fail getting renamed correctly. Refer https://github.com/ppc64le-cloud/docker-ce-build/blob/main/build-static.sh#L75
> Change DOCKER_REF to DOCKER_TAG in build-static

- test-containerd/test_on_powervs.sh
Set the crun version to the same version that is pinned by the containerd project.
> Set crun version to pinned version

- upstream-master-ci/build-dev-image.sh
- upstream-master-ci/integration-tests.sh
- upstream-master-ci/prow-integration-tests.sh
- upstream-master-ci/prow-unit-test-docker.sh
- upstream-master-ci/unit-tests.sh
Reduce the amount of code and avoid doing a direct `docker run` against [moby](https://github.com/moby/moby/) repository and instead use their [Makefile](https://github.com/moby/moby/blob/master/Makefile) for the tests.
> Upstream CI unit and integration test updates

- upstream-master-ci/integration-tests.sh
If using `cgroup v2`, [integration-cli tests don't run](https://github.com/moby/moby/blob/master/Makefile#L64) [unless the cgroup check is skipped](https://github.com/moby/moby/commit/c2004fb8c4fdea8d48296f7ba92bcf981ba86978).
So skip it by [setting that variable](https://github.com/ppc64le-cloud/docker-ce-build/pull/198/files#diff-87ace9015eee2a9dfe41dd497701bd510b6671dd1228fa01f0f428a13588f443R6).
> Skip cgroup version check to prevent integration CI test error

- get-env-containerd.sh
This temporary fix is no longer required.
> Use latest CentOS version for tests

- upstream-master-ci/prow-unit-test-docker.sh
By default, Kubernetes sets `ndots:5` in `/etc/resolv.conf` causing [TestDNSOptions](https://github.com/moby/moby/blob/master/libnetwork/sandbox_dns_unix_test.go#L42) to fail in our ProwJob setup. The solution is to manually override `ndots` to 0 after starting dockerd. However, we cannot perform this replacement directly in the original file, otherwise we get an error `Device busy`.
> Change ndots to 0 after starting dockerd

- upstream-master-ci/build-dev-image.sh
- upstream-master-ci/get-env-ci.sh
- upstream-master-ci/info.sh
- upstream-master-ci/integration-tests.sh
- upstream-master-ci/prow-info-docker.sh
- upstream-master-ci/unit-tests.sh
We run _check config_, _build-dev-image_, _unit_ and _integration_ tests against [github.com/moby/moby](github.com/moby/moby). Store these logs to our COS bucket so they're not merely displayed on the terminal and can be reviewed later. The parent folder will be the shortened commit id of the latest commit against [github.com/moby/moby](github.com/moby/moby) and inside it, you will find `.log` files corresponding to the respective test suites (e.g. `202de33/integration.log`).
> Store CI logs

- upstream-master-ci/prow-unit-test-docker.sh
We hoped https://github.com/ppc64le-cloud/docker-ce-build/pull/209/commits/176bbe167dec0c4a0ea966eef681173cb944e7ec will solve the unit test failure that checks ndots = 0 but it causes `dockerd` to not start whereas https://github.com/ppc64le-cloud/docker-ce-build/pull/209/commits/1bd3b015c364d6e69e2fbc053674c07fdeb6dd59 is not an elegant solution but makes the test pass at least.
> Set ndots to 0 in /etc/resolv.conf instead of dockerd flag

- env/env.list
Test whether COS bucket mounts successfully by doing a dummy run.
> Test COS bucket mount

- env/env.list
- images/docker-in-docker/Dockerfile
- test-DEBS/Dockerfile
- test-RPMS/Dockerfile
- test-repo-DEBS/Dockerfile
- test-repo-RPMS/Dockerfile
- test-static-alpine/Dockerfile
A Docker image was built using https://github.com/ppc64le-cloud/docker-ce-build/compare/main...AshwinHIBM:docker-ce-build:0.9-ppc64le?expand=1#diff-c21b6a06ad8e557007d6d6b5d01fa16331d6d42b8cece38b90d15cf05b3c18d1 and tagged [0.9-ppc64le](https://quay.io/repository/powercloud/docker-ce-build/manifest/sha256:f93b6d36ad414d30f584c6555d8c2116de58bd56601da36f4e13d4b5b624114a). Update the Dockerfile here for keeping a record. Also propagate the same updates across the test Dockerfiles.
Also change `CONTAINERD_BUILD` to 1 so we can build Docker and containerd in one go.
Also build Docker v27.1.0 and containerd v1.7.19.
> 0.9-ppc64le DinD image for build and tests

- env/env.list
Copied containerd v1.7.19 packages to prow-docker/ in the COS bucket. Run tests using these.
> Test using containerd v1.7.19

- env/test-staging.list
Re-trigger Docker 27.1.0 and containerd 1.7.19 tests due to absence of containerd in the expected folder.
> Re-trigger Docker 27.1.0 and containerd 1.7.19 tests

- upstream-master-ci/unit-tests.sh
We're currently reporting an error code despite no unit test failures. Fix it by returning the correct error code.
> Report success if unit tests pass or are skipped

- upstream-master-ci/integration-tests.sh
[Integration CLI tests present in the moby repository are deprecated](https://github.com/moby/moby/blob/master/TESTING.md#writing-new-integration-tests). Stop running them. This also includes a commit to return the correct exit code from integration tests.
> Block integration cli from main suite

- upstream-master-ci/integration-cli.sh
- upstream-master-ci/prow-integration-cli.sh
Scripts to run tests in https://github.com/docker/cli.
The job triggering this script: https://github.com/ppc64le-cloud/test-infra/pull/483
> Integration CLI tests

- env/test-staging.list
Packages weren't available, they are now. Retest.
> Retest Docker v27.3.0 and containerd v1.7.22 staging

- build-containerd.sh
- test.sh
Use CentOS Stream 10 instead of CentOS 10 and get it from quay.io. This PR also includes some minor code style changes.
> Switch to CentOS Stream 10

- get-env-test.sh
- test-launch.sh
- test.sh
Obtain the expected `runc` version if unspecified and compare it against the one installed as a part of pre-test validation for dynamic binaries. This PR also removes all the version checks for Docker CLI, Docker Engine and containerd versions for static binaries as static binaries follow a different naming convention for versions.
> Obtain expected runc version programmatically while testing dynamic binaries

- README.md
- env/env.list
- get-env.sh
The Docker CLI and Engine repositories are tagged by their version, e.g. v27.4.1. Use tags to checkout these repositories rather than hashes. This saves our efforts by not requiring specifying the hashes for each of these repositories separately. This also eliminates the chance of human error caused by entering a wrong hash for either of the repositories.
> Use a single tag for building the CLI and Engine

- get-env-test.sh
https://github.com/ppc64le-cloud/docker-ce-build/pull/247 did not set FILE_ENV to env.list. Set it.
> Set FILE_ENV for sourcing CONTAINERD_TAG in tests

- check-tests.sh
False errors show up when distribution names contain the number 1. This code fix counts the actual errors instead of looking for the number 1.
Closes #260
> Fix false errors that show despite no errors

- build-containerd.sh
- build-docker.sh
- build-static.sh
- env/env.list
- test.sh
None of the upstream files use Debian-Buster or Ubuntu-Impish anymore. Remove the workarounds that were in place earlier because these distributions were present in the upstream repository/repositories
> Remove Debian-Buster and Ubuntu-Impish exclusion workarounds

- upstream-master-ci/prow-info-docker.sh
Since the current date is stored in PATH_SCRIPTS/env/date.list while running periodic-info-docker, we need to pass in this filepath to the script that triggers the next postsubmit CI jobs
> CI bugfix: Add source file to get date to commit to prow-job-tracking branch

- test-DEBS/Dockerfile
- test-repo-DEBS/Dockerfile
software-properties-common is not required for us and not supported in Debian Trixie
> Remove software-properties-common from Debian test Dockerfiles

- env/env.list
- images/docker-in-docker/Dockerfile
- test-DEBS/Dockerfile
- test-RPMS/Dockerfile
- test-launch.sh
- test-repo-DEBS/Dockerfile
- test-repo-RPMS/Dockerfile
- test-static-alpine/Dockerfile
- upstream-master-ci/integration-cli.sh
Update the scripts to use the updated 1.1-ppc64le Docker-in-Docker image. The scripts include updates to the Go version for the tests, Docker buildx plugin version update and update to the Docker version.
The jobs that will run the scripts can be found here: https://github.com/ppc64le-cloud/test-infra/pull/567
The updated image can be found here: https://quay.io/repository/powercloud/docker-ce-build/manifest/sha256:ecb898a3ce053b49c21e06cb7c762017d1b0f8ec87dade76c52324c5566b5f30
> 1.1-ppc64le Docker-in-Docker image
