build.sh
=> Fix containerd

test.sh
=> Fix test.sh

test-containerd/instanciate_powervs_vm.sh
=> Use the right test file

env/env.list
Update settings for building those new releases
=> Build: docker 20.10.13 and containerd.io v1.5.10 (with runc v1.0.3)

env/env.list
This is a test of docker build from prow-job.
=> Docker build from prow-job

test-containerd/instanciate_powervs_vm.sh
Change timeout and add a restart if grub trouble.
=> Workaround PowerVS trouble

push-COS.sh
Output summary at the end of log.
Example:
``` ---------------------------------------------------------
COS bucket directory -> packages version :
containerd-1.6-2 -> containerd v1.6.4
docker-ce-20.10-27 -> docker v20.10.15
---------------------------------------------------------```
=> Add a summary for push_COS.sh

build-docker.sh
Now, there will be always "max" builds being run in parallel.
=> Improve the paralelized build

build-containerd.sh
This is made the same way it was done for improving the building of Docker.
=> Add parallelization of building&testing containerd

build-containerd.sh
- Add the final "&" of buildContainerd
- Remove ubuntu-impish from the list of Distros
- Use the number of CPUs for the "max" parallelism
- Factorize building the list of Distros
=> Fix issues of parallelism

build-containerd.sh
Clone containerd-packaging once and then duplicate the code for each Distro into a specific directory.
=> Use a specific directory for each distro

env/env.list
Relaunch build/tests now that cluster is back in order to get more traces for analyzing the current issue
=> Retry build after cluster reboot

build-static.sh
=> Fix buster/bullseye in correct Makefiles

build-docker.sh
Add more trace for debugging static build issue: display options.
=> Add more trace

build-static.sh
Search for buster anywhere about static build issue with Go.
=> Search for buster anywhere

test-containerd/instantiate_vm_and_test.sh
Wait for instance to reboot before retrying ssh connection.
=> Wait for instance reboot

env/test-staging.list
Retesting Docker 20.10.24 in staging as the last time a few tests failed as the docker daemon didn't start
=> Retest Docker 20.10.24 in staging

env/test-staging.list
Docker daemon did not start for some distributions.
=> Retest staging Docker v23.0.5

env/test-release.list
Docker daemon did not start for some distributions.
=> Retest release Docker v23.0.6

env/test-staging.list
Docker daemon did not start for some distributions.
=> Retest staging Docker v24.0.0

env/env.list
Building for a single distribution doesn't seem to work
=> Rebuild Docker v24.0.2

README.md
=> ReadMe corrections

env/test-staging.list
2 distributions failed to test
=> Retest staging Docker v24.0.3 due to random GLIBC errors

env/env.list
=> Build Docker v25.0.4

test-DEBS/Dockerfile, test-RPMS/Dockerfile, test-repo-DEBS/Dockerfile, test-repo-RPMS/Dockerfile, test.sh
Get the latest Go version automatically for running tests
=> Get the latest Go version for tests

test-containerd/instantiate_vm_and_test.sh
Update ibmcloud commands to match the new interface for the new power-iaas plugin version.
=> Update ibmcloud commands

env/test-release.list, test-launch.sh
Verify that the versions of `Docker Server`, `CLI`, `containerd` and `runc` installed in the test containers is indeed the ones we intend to test.
=> Get Docker server, CLI, containerd and runc versions and compare

env/env.list
=> Build Docker v27.2.0 and containerd v1.7.22

upstream-master-ci/prow-build-dev-image.sh, upstream-master-ci/prow-info-docker.sh
prow-config-docker.sh and prow-build-dev-image-docker.sh display generic messages before starting up. Display specific messages identifying the specific script that is being run
=> Update periodic CI script introductory display messages

env/env.list
containerd v1.7.27 is already built
=> Build Docker v28.1.0
